name: Download and Process Archive

on:
  workflow_dispatch:

jobs:
  process-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download and process archive
        run: |
          python -c '
          import requests
          import zipfile
          import os
          import shutil
          
          # Wayback Machine URL
          archive_url = "https://web.archive.org/web/20090729072837/http://downloads.de-cendres.net/mirrors/EVAcompi.zip"
          
          try:
              # Create a directory for the download
              if not os.path.exists("temp"):
                  os.makedirs("temp")
              
              # Download the file
              print("Downloading archive...")
              response = requests.get(archive_url, stream=True)
              response.raise_for_status()
              
              # Save the downloaded file
              zip_path = os.path.join("temp", "archive.zip")
              with open(zip_path, "wb") as f:
                  for chunk in response.iter_content(chunk_size=8192):
                      f.write(chunk)
              
              # Create albums directory if it doesnt exist
              if not os.path.exists("albums"):
                  os.makedirs("albums")
              
              # Extract the ZIP file
              print("Extracting archive...")
              with zipfile.ZipFile(zip_path, "r") as zip_ref:
                  zip_ref.extractall("albums")
              
              # Clean up temporary files
              shutil.rmtree("temp")
              
              print("Archive processed successfully!")
              
          except Exception as e:
              print(f"Error occurred: {str(e)}")
              raise e
          '

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add albums/
          git commit -m "Add processed archive contents"
          git push
